language: python
python:
  - 3.6
  - pypy3
jobs:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
script:
  - pip install coveralls pytest pytest-cov
  - ./setup.py test
after_script:
  - coveralls
